debug: false

server:
  port: 8082
  error:
    include-message: always
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: utf-8
    context-path: /

spring:
  application:
    name: JM Spring Boot Security with Fetch API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Europe/Moscow&useLegacyDatetimeCode=false
    username: root
    password: subretjokerzona173873b
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          charset_name: UTF-8
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    add-properties: true
  web:
    locale: ru_RU
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  charset:
    console: UTF-8
